# Generated by Django 2.0.10 on 2019-06-28 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encargado', to=settings.AUTH_USER_MODEL)),
                ('Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trabajador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Mensaje', models.CharField(blank=True, max_length=50, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Informacion', models.TextField()),
                ('Asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.NullBooleanField(default=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(blank=True, max_length=20, null=True)),
                ('Telefono_C', models.CharField(blank=True, max_length=50, null=True)),
                ('Telefono_F', models.CharField(blank=True, max_length=50, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=400, null=True)),
                ('Comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('Ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('Tipo', models.CharField(blank=True, choices=[('EN', 'Encargado'), ('TR', 'Trabajador')], max_length=2, null=True)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Mensaje')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Informacion', models.TextField()),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Mensaje')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Informacion', models.TextField()),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Respuesta')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Situacion_Clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contacto_Numero', models.CharField(blank=True, max_length=50, null=True)),
                ('Detalle', models.CharField(blank=True, max_length=50, null=True)),
                ('Enfermedad', models.CharField(blank=True, max_length=50, null=True)),
                ('Contacto_Nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
