# Generated by Django 2.0.10 on 2019-06-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='Encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encargado', to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='Trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trabajador', to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Persona'),
        ),
        migrations.AlterField(
            model_name='respuesta_respuesta',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Persona'),
        ),
    ]
