# Generated by Django 2.0.10 on 2019-07-08 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20190628_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.TextField()),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emiso', to='Core.Persona')),
                ('Receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receptor', to='Core.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='Nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
